# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areaed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areastr', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('areadate', models.BigIntegerField()),
                ('goodsid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsName', models.CharField(max_length=255, null=True)),
                ('goodsImg', models.ImageField(null=True, upload_to='img')),
                ('manageDepartment', models.CharField(max_length=255, null=True)),
                ('useDepartment', models.CharField(max_length=255, null=True)),
                ('manager', models.CharField(max_length=255, null=True)),
                ('user', models.CharField(max_length=255, null=True)),
                ('recorder', models.CharField(max_length=255, null=True)),
                ('recordDate', models.BigIntegerField(null=True)),
                ('size', models.CharField(max_length=255, null=True)),
                ('color', models.CharField(max_length=255, null=True)),
                ('modelNum', models.CharField(max_length=255, null=True)),
                ('financeRecord', models.IntegerField(null=True)),
                ('area', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
