# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='recordNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsId', models.IntegerField()),
                ('recordId', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='areaed',
            name='username',
        ),
    ]
